### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by ZhouCX117** [nus-vv-streams/lapis-gs#2]
Thank you for your excellent work. May I kindly ask about your code release plan?

**Comment by Shiyuang-scu** [comment]
Hey, thank you for your interest! We are cleaning and packing the code, and will release the code in a few days.

**Comment by ZhouCX117** [comment]
Hi @Shiyuang-scu, thank you for sharing your code. After reading the paper and the codes, I am still unsure about the difference between opacity and occupancy maps. Could you please explain it further?

**Comment by Shiyuang-scu** [comment]
Hi, in short, they are essentially the same but used in different scenarios. 

Our work comes from the perspective of streaming. In the scenario of streaming, an occupancy map provides a compact and binary representation of the scene, which can be used for streaming, leading to more efficient use of bandwidth. For example, with an occupancy map, the encoder can identify the regions of the scene which are more important. It can then allocate more encoding resources and bandwidth to these regions of importance, while compressing less important areas more aggressively. In this usage scenario, we don't need to transmit the full range of values of opacity, but only an occupancy map with 1 and 0.
