### ISSUE TITLE
Question about smooth transition in paper Figure5. 

### ISSUE THREAD

**Issue by Sunnyhong0326** [nus-vv-streams/lapis-gs#4]
Hi, thanks for your excellent work!
In the paper, Figure 5 demonstrates the smooth transition from one level to another level. In the code, do you implement this smooth transition? If so, how can I visualize it?

**Comment by Shiyuang-scu** [comment]
Hey, thank you for your interest! We didn't include the implementation of level transition in this repo. 

In this paper, we focus on building a "streamable" representation for 3DGS, and only showcase the potential of smooth level switch with naive linear interpolation on opacity. The performance of the smooth transition method still requires further rigorous validation. Currently, we are adapting this representation to build a 3DGS streaming system, where we may see a more sophisticated implementation.
